package agendasencilla;

import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author tinit
 */
public class interfazAgendaSencilla extends javax.swing.JFrame {

    public Connection conectar() {
        String usuario = "root"; // Esto se puede tomar por pantalla en un text field
        String contrasena = "";
        String url = "jdbc:mysql://localhost:3306/agenda"; // Generalmente el puerto es el 3306
        Connection con = null; // Para empezar se comienza en null porque retornamos datos
        try {
            con = DriverManager.getConnection(url, usuario, contrasena); // Recibe estos parámetros
            return con; // Retorna la conexión
        } catch (Exception e) { // Si el Try no funciona se realiza el catch
            return null; // Retorna una conexion negativa cerrada
        } // Fin Try Catch

    }  // Fin public class interfazAgendaSencilla extends javax.swing.JFrame 

    // Modelo para manipular la tabla
    DefaultTableModel modelo;

    public interfazAgendaSencilla() {
        initComponents();

        //inicio el modelo para manipular la tabla
        modelo = (DefaultTableModel) tabla.getModel();

        // Mostrar líneas de la tabla
        tabla.setShowHorizontalLines(true);
        tabla.setShowVerticalLines(true);

        // Color de las líneas
        tabla.setGridColor(java.awt.Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_Telefono1 = new javax.swing.JLabel();
        telefono1 = new javax.swing.JTextField();
        L_Titulo = new javax.swing.JLabel();
        L_Nombres = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        L_Apellidos = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        L_Telefono = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        L_Dirección = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        L_Dirección1 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        B_Agregar = new javax.swing.JButton();
        B_Consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        B_BorrarContacto = new javax.swing.JButton();
        B_EditarContacto = new javax.swing.JButton();
        B_ListarCiudad = new javax.swing.JButton();
        B_ListarRangoID = new javax.swing.JButton();
        L_RangosID = new javax.swing.JLabel();
        idInicial = new javax.swing.JTextField();
        L_IdInicial1 = new javax.swing.JLabel();
        idFinal = new javax.swing.JTextField();
        L_IdInicial2 = new javax.swing.JLabel();

        L_Telefono1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Telefono1.setText("Teléfono:");

        telefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        L_Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L_Titulo.setText("Agenda telefónica");

        L_Nombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Nombres.setText("Nombres:");

        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });

        L_Apellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Apellidos.setText("Apellidos:");

        apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosActionPerformed(evt);
            }
        });

        L_Telefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Telefono.setText("Teléfono:");

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });

        L_Dirección.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Dirección.setText("Dirección:");

        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });

        L_Dirección1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Dirección1.setText("E-Mail:");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        B_Agregar.setText("Agregar");
        B_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AgregarActionPerformed(evt);
            }
        });

        B_Consultar.setText("Consultar");
        B_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ConsultarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Telefono", "Direccion", "Email"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane2.setViewportView(salida);

        B_BorrarContacto.setText("Borrar contacto");
        B_BorrarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BorrarContactoActionPerformed(evt);
            }
        });

        B_EditarContacto.setText("Editar contacto");
        B_EditarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EditarContactoActionPerformed(evt);
            }
        });

        B_ListarCiudad.setText("Listar por ciudad");
        B_ListarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ListarCiudadActionPerformed(evt);
            }
        });

        B_ListarRangoID.setText("Listar rango ID");
        B_ListarRangoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ListarRangoIDActionPerformed(evt);
            }
        });

        L_RangosID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_RangosID.setText("Rangos de ID: ");

        idInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInicialActionPerformed(evt);
            }
        });

        L_IdInicial1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_IdInicial1.setText("ID final:");

        idFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFinalActionPerformed(evt);
            }
        });

        L_IdInicial2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_IdInicial2.setText("ID inicial:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_Titulo)
                .addGap(268, 268, 268))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_ListarRangoID)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(L_Nombres)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(L_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(L_Dirección)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(L_Dirección1)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(L_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(email)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(B_Agregar)
                                    .addGap(46, 46, 46)
                                    .addComponent(B_Consultar)
                                    .addGap(37, 37, 37)
                                    .addComponent(B_BorrarContacto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(B_EditarContacto)
                                    .addGap(39, 39, 39)
                                    .addComponent(B_ListarCiudad))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L_RangosID)
                                    .addGap(31, 31, 31)
                                    .addComponent(L_IdInicial2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L_IdInicial1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(L_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Nombres)
                    .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Apellidos)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Telefono)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Dirección)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Dirección1)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_RangosID)
                    .addComponent(L_IdInicial2)
                    .addComponent(idInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_IdInicial1)
                    .addComponent(idFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Agregar)
                    .addComponent(B_Consultar)
                    .addComponent(B_BorrarContacto)
                    .addComponent(B_EditarContacto)
                    .addComponent(B_ListarCiudad))
                .addGap(11, 11, 11)
                .addComponent(B_ListarRangoID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void telefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono1ActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void B_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AgregarActionPerformed

        Connection con = conectar();
        if (con != null) {
            if (!nombres.getText().isEmpty() && !apellidos.getText().isEmpty() && !telefono.getText().isEmpty() && !direccion.getText().isEmpty() && !email.getText().isEmpty()) {
                String query = "INSERT INTO datos(id,nombres,apellidos,telefono,direccion,email) VALUES (null,'" + nombres.getText() + "','" + apellidos.getText() + "','" + telefono.getText() + "','" + direccion.getText() + "','" + email.getText() + "');";

                try {
                    //preparo la consulta
                    PreparedStatement preparar = con.prepareStatement(query);
                    //ejecuto la consulta luego de prepararla, cuando la consulta es insert, update, delete etc, devuelve un entero con el número de filas afectadas
                    preparar.executeUpdate();
                    salida.setText("Consulta correcta");
                } catch (SQLException ex) {
                    salida.setText("Error en la consulta");
                }
            } else {
                System.out.println("Los campos estan vacios. ");
            }
        } else {
            System.out.println("No se pudo conectar con el servidor. ");
        }

    }//GEN-LAST:event_B_AgregarActionPerformed

    private void B_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ConsultarActionPerformed
        //limpio la tabla antes de llevar los valores
        modelo.setRowCount(0);
        Connection con = conectar();
        String query = "SELECT * FROM datos;";
        try {
            //preparo la consulta
            PreparedStatement preparar = con.prepareStatement(query);
            //ejecuto la consulta luego de prepararla, como es un select devuelve una lista de tipo ResultSet
            ResultSet resultado = preparar.executeQuery();
            //hago un ciclo para recorrer la lista y ponerla en la tabla de la interfaz
            while (resultado.next()) {
                modelo.addRow(new Object[]{resultado.getInt("id"), resultado.getString("nombres"), resultado.getString("apellidos"), resultado.getString("telefono"), resultado.getString("direccion"), resultado.getString("email")});
            }
            salida.setText("Conexión correcta"); // si lo de arriba se hizo, devuelve la salida correcta
        } catch (SQLException ex) {
            System.out.println("Error en el sql");
        }

    }//GEN-LAST:event_B_ConsultarActionPerformed

    private void B_BorrarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarContactoActionPerformed
        Connection con = conectar();
        if (con != null) {
            if (!telefono.getText().isEmpty()) {
                String query = "DELETE FROM datos WHERE telefono = '" + telefono.getText() + "' ; ";

                try {
                    //preparo la consulta
                    PreparedStatement preparar = con.prepareStatement(query);
                    //ejecuto la consulta luego de prepararla, cuando la consulta es insert, update, delete etc, devuelve un entero con el número de filas afectadas
                    if (preparar.executeUpdate() > 0) { // mientras el numero de filas afectadas sea mayor que 0, quiere decir que SI se realizó un cambio.
                        salida.setText("El contacto  se borró correctamente. ");
                    } else { // si el numero de filas afectadas es 0, quiere decir que NO se realizó un cambio.
                        salida.setText("El teléfono ingresado no existe  ");
                    }
                } catch (SQLException ex) {
                    salida.setText("Error: no se borró el contacto. ");
                }
            } else {
                salida.setText("No se ha ingresado un teléfono. ");
            }
        } else {
            salida.setText("No se pudo conectar con el servidor. ");
        }
    }//GEN-LAST:event_B_BorrarContactoActionPerformed

    private void B_EditarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EditarContactoActionPerformed
        Connection con = conectar();
        if (con != null) {
            if (!telefono.getText().isEmpty()) {

                if (nombres.getText().isEmpty() || apellidos.getText().isEmpty() || telefono.getText().isEmpty() || direccion.getText().isEmpty() || email.getText().isEmpty()) {
                    salida.setText("Los campos estan vacios o incompletos. Llene todos los campos. ");
                } else {

                    String query = "UPDATE `datos` SET nombres='" + nombres.getText() + "' , apellidos= '" + apellidos.getText() + "' , telefono= '" + telefono.getText() + "', direccion='" + direccion.getText() + "', email='" + email.getText() + "' WHERE telefono = '" + telefono.getText() + "' ; ";

                    try {
                        //preparo la consulta
                        PreparedStatement preparar = con.prepareStatement(query);
                        //ejecuto la consulta luego de prepararla, cuando la consulta es insert, update, delete etc, devuelve un entero con el número de filas afectadas
                        if (preparar.executeUpdate() > 0) { // mientras el numero de filas afectadas sea mayor que 0, quiere decir que SI se realizó un cambio.
                            salida.setText("El contacto  se actualizó correctamente. ");
                        } else { // si el numero de filas afectadas es 0, quiere decir que NO se realizó un cambio.
                            salida.setText("El contacto ingresado no existe  ");
                        }
                    } catch (SQLException ex) {
                        salida.setText("Error: no se actualizó el contacto. ");
                    }
                }
            } else {
                salida.setText("No se ha ingresado un teléfono para actualizar un contacto. ");
            }
        } else {
            salida.setText("No se pudo conectar con el servidor. ");
        }
    }//GEN-LAST:event_B_EditarContactoActionPerformed

    private void B_ListarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ListarCiudadActionPerformed
        Connection con = conectar();
        modelo.setRowCount(0);

        if (con != null) {
            if (!direccion.getText().isEmpty()) {
                if (direccion.getText().isEmpty()) {
                    salida.setText("El campo -Direccion- está vacio. Llene el campo");
                } else {
                    String query = "SELECT * FROM datos WHERE direccion LIKE '%" + direccion.getText() + "%' ;";

                    try {
                        //preparo la consulta
                        PreparedStatement preparar = con.prepareStatement(query);
                        //ejecuto la consulta luego de prepararla, como es un select devuelve una lista de tipo ResultSet
                        ResultSet resultado = preparar.executeQuery();
                        //hago un ciclo para recorrer la lista y ponerla en la tabla de la interfaz
                        boolean ciudad = false;
                        while (resultado.next()) {
                            modelo.addRow(new Object[]{resultado.getInt("id"), resultado.getString("nombres"), resultado.getString("apellidos"), resultado.getString("telefono"), resultado.getString("direccion"), resultado.getString("email")});
                            ciudad = true;
                        }
                        if (ciudad) {
                            salida.setText("Listado de la ciudad " + direccion.getText() + "."); // si lo de arriba se hizo, devuelve la salida correcta
                        } else {
                            salida.setText("No se encuentra la ciudad. ");
                        }

                    } catch (SQLException ex) {
                        salida.setText("Error en el sql");
                    }
                }
            } else {
                salida.setText("No se ha ingresado una dirección para buscar los contactos. ");
            }
        } else {
            salida.setText("No se pudo conectar con el servidor. ");
        }
    }//GEN-LAST:event_B_ListarCiudadActionPerformed

    private void B_ListarRangoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ListarRangoIDActionPerformed
        Connection con = conectar();
        modelo.setRowCount(0);

        if (con != null) {
            if (!idInicial.getText().isEmpty() || !idFinal.getText().isEmpty()) {
                if (idInicial.getText().isEmpty() || idFinal.getText().isEmpty()) {
                    salida.setText("El campo -Id Inicial- y/o -Id Final- está/n vacio/s. Llene los campos");
                } else {
                    String query = "SELECT * FROM datos WHERE id BETWEEN ' " + idInicial.getText() + " ' AND '" + idFinal.getText() + "' ;";

                    try {
                        //preparo la consulta
                        PreparedStatement preparar = con.prepareStatement(query);
                        //ejecuto la consulta luego de prepararla, como es un select devuelve una lista de tipo ResultSet
                        ResultSet resultado = preparar.executeQuery();
                        //hago un ciclo para recorrer la lista y ponerla en la tabla de la interfaz
                        boolean id = false;
                        while (resultado.next()) {
                            modelo.addRow(new Object[]{resultado.getInt("id"), resultado.getString("nombres"), resultado.getString("apellidos"), resultado.getString("telefono"), resultado.getString("direccion"), resultado.getString("email")});
                            id = true;
                        }
                        if (id) {
                            salida.setText("Listado por id en rango " + idInicial.getText() + " y " + idFinal.getText() + "."); // si lo de arriba se hizo, devuelve la salida correcta
                        } else {
                            salida.setText("No se encuentran los rangos de ID. ");
                        }

                    } catch (SQLException ex) {
                        salida.setText("Error en el sql");
                    }
                }
            } else {
                salida.setText("No se ha ingresado un Id para buscar los contactos. ");
            }
        } else {
            salida.setText("No se pudo conectar con el servidor. ");
        }
    }//GEN-LAST:event_B_ListarRangoIDActionPerformed

    private void idInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInicialActionPerformed

    private void idFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFinalActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazAgendaSencilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazAgendaSencilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazAgendaSencilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazAgendaSencilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazAgendaSencilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Agregar;
    private javax.swing.JButton B_BorrarContacto;
    private javax.swing.JButton B_Consultar;
    private javax.swing.JButton B_EditarContacto;
    private javax.swing.JButton B_ListarCiudad;
    private javax.swing.JButton B_ListarRangoID;
    private javax.swing.JLabel L_Apellidos;
    private javax.swing.JLabel L_Dirección;
    private javax.swing.JLabel L_Dirección1;
    private javax.swing.JLabel L_IdInicial1;
    private javax.swing.JLabel L_IdInicial2;
    private javax.swing.JLabel L_Nombres;
    private javax.swing.JLabel L_RangosID;
    private javax.swing.JLabel L_Telefono;
    private javax.swing.JLabel L_Telefono1;
    private javax.swing.JLabel L_Titulo;
    private javax.swing.JTextField apellidos;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField email;
    private javax.swing.JTextField idFinal;
    private javax.swing.JTextField idInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextArea salida;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField telefono1;
    // End of variables declaration//GEN-END:variables
}
